# Generated by cpp11: do not edit by hand

read_dic_ <- function(filepath) {
  .Call(`_redatam_read_dic_`, filepath)
}

print_rbf_paths_with_logging <- function(path, rbf_paths, entityName, parentName) {
  .Call(`_redatam_print_rbf_paths_with_logging`, path, rbf_paths, entityName, parentName)
}
