# Generated by cpp11: do not edit by hand

read_dic_ <- function(filepath) {
  .Call(`_redatam_read_dic_`, filepath)
}

read_rbf_ <- function(variable_meta) {
  .Call(`_redatam_read_rbf_`, variable_meta)
}
