# Generated by cpp11: do not edit by hand

export_redatam_to_csv_ <- function(dicFilePath, outputDirPath) {
  .Call(`_redatam_export_redatam_to_csv_`, dicFilePath, outputDirPath)
}

export_redatam_to_list_ <- function(dicFilePath) {
  .Call(`_redatam_export_redatam_to_list_`, dicFilePath)
}
