// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// read_dic.cpp
list read_dic_(const std::string& filepath);
extern "C" SEXP _redatam_read_dic_(SEXP filepath) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_dic_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(filepath)));
  END_CPP11
}
// read_ptr_rbf.cpp
list parse_ptr_(const std::string& path);
extern "C" SEXP _redatam_parse_ptr_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(parse_ptr_(cpp11::as_cpp<cpp11::decay_t<const std::string&>>(path)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_redatam_parse_ptr_", (DL_FUNC) &_redatam_parse_ptr_, 1},
    {"_redatam_read_dic_",  (DL_FUNC) &_redatam_read_dic_,  1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_redatam(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
