// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// main.cpp
cpp4r::list export_redatam_to_list_(std::string dicFilePath);
extern "C" SEXP _redatam_export_redatam_to_list_(SEXP dicFilePath) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(export_redatam_to_list_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(dicFilePath)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_redatam_export_redatam_to_list_", (DL_FUNC) &_redatam_export_redatam_to_list_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_redatam(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
