name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.0-gtk3-dev

      - name: Set up environment on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install wxwidgets
          echo "$(brew --prefix wxwidgets)/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=$(brew --prefix wxwidgets)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install Xerces on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          chmod +x dev/01-install-xerces.sh
          ./dev/01-install-xerces.sh

      - name: Install Xerces on macOS
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x dev/01-install-xerces.sh
          ./dev/01-install-xerces.sh

      - name: Build redatam on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: make all

      - name: Build redatam and redatamgui on macOS
        if: matrix.os == 'macos-latest'
        run: make all

      - name: Upload binaries on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binaries
          path: |
            redatam
            redatamgui

      - name: Upload binaries on macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            redatam
            redatamgui
