name: Standalone C++ app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev

      - name: Set up environment on Mac
        if: matrix.os == 'macos-14'
        run: |
          brew install qt@5
          echo "/opt/homebrew/opt/qt@5/bin" >> $GITHUB_PATH
          echo "LDFLAGS=-L/opt/homebrew/opt/qt@5/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/qt@5/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/qt@5/lib/pkgconfig" >> $GITHUB_ENV

      - name: Set up environment on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System' --apply-install-arguments-to-dependencies

      - name: Install Qt on Windows
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\Qt'

      - name: Build redatam and redatamgui on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: make all

      - name: Build redatam and redatamgui on Mac
        if: matrix.os == 'macos-14'
        run: make all

      - name: Build redatam on Windows
        if: matrix.os == 'windows-latest'
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          nmake redatam

      - name: Build redatamgui on Windows
        if: matrix.os == 'windows-latest'
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH="C:/Qt/5.15.2/msvc2019_64" ..
          cmake --build . --config Release
          "C:\Qt\5.15.2\msvc2019_64\bin\windeployqt.exe" --release .\redatamgui.exe

      - name: Test redatam with a DIC file on Mac/Linux
        if: matrix.os != 'windows-latest'
        run: ./redatam test/galapagos/cg15.dic test/galapagos/dic-to-csv

      - name: Test redatam with a DICX file on Mac/Linux
        if: matrix.os != 'windows-latest'
        run: ./redatam test/galapagos/cg15.dicX test/galapagos/dicx-to-csv

      - name: Test redatam with a DIC file on Windows
        if: matrix.os == 'windows-latest'
        run: .\build\Release\redatam.exe test\galapagos\cg15.dic test\galapagos\dic-to-csv

      - name: Test redatam with a DICX file on Windows
        if: matrix.os == 'windows-latest'
        run: .\build\Release\redatam.exe test\galapagos\cg15.dicX test\galapagos\dicx-to-csv

      - name: Create DEB package on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/share/applications
          cp redatam package/usr/local/bin/
          cp redatamgui package/usr/local/bin/
          chmod +x package/usr/local/bin/redatam
          chmod +x package/usr/local/bin/redatamgui
          echo "[Desktop Entry]
          Version=1.0
          Name=Redatam GUI
          Exec=/usr/local/bin/redatamgui
          Icon=utilities-terminal
          Type=Application
          Categories=Utility;" > package/usr/share/applications/redatamgui.desktop
          mkdir -p package/DEBIAN
          echo "Package: redatam
          Version: 0.0.1
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Mauricio Pacha Vargas Sepulveda <m.sepulveda@mail.utoronto.ca>
          Depends: qtbase5-dev
          Description: Redatam and Redatam GUI" > package/DEBIAN/control
          dpkg-deb --build package redatam_0.0.1_amd64.deb

      - name: Upload DEB on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-deb
          path: |
            redatam_0.0.1_amd64.deb

      - name: Upload binaries on Mac
        if: matrix.os == 'macos-14'
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            redatam
            redatamgui

      - name: Upload binaries on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: |
            build/Release/redatam.exe
            build/Release/redatamgui.exe
