name: Build Ubuntu executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev

      - name: Build redatam and redatamgui on Ubuntu
        run: make all

      - name: Test redatam with a DIC file on Ubuntu
        run: ./redatam test/galapagos/cg15.dic test/galapagos/dic-to-csv

      - name: Test redatam with a DICX file on Ubuntu
        run: ./redatam test/galapagos/cg15.dicX test/galapagos/dicx-to-csv

      - name: Create DEB package on Ubuntu
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/share/applications
          cp redatam package/usr/local/bin/
          cp redatamgui package/usr/local/bin/
          chmod +x package/usr/local/bin/redatam
          chmod +x package/usr/local/bin/redatamgui
          echo "[Desktop Entry]
          Version=1.0
          Name=Redatam GUI
          Exec=/usr/local/bin/redatamgui
          Icon=utilities-terminal
          Type=Application
          Categories=Utility;" > package/usr/share/applications/redatamgui.desktop
          mkdir -p package/DEBIAN
          echo "Package: redatam
          Version: 0.1
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Mauricio Pacha Vargas Sepulveda <m.sepulveda@mail.utoronto.ca>
          Depends: qtbase5-dev
          Description: Redatam and Redatam GUI" > package/DEBIAN/control
          dpkg-deb --build package redatam_0.1_amd64.deb

      - name: Upload DEB on Ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: redatam-ubuntu
          path: |
            redatam_0.1_amd64.deb
