name: Standalone C++ app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev

      - name: Set up environment on Mac
        if: matrix.os == 'macos-14'
        run: |
          brew install qt@5
          echo "/opt/homebrew/opt/qt@5/bin" >> $GITHUB_PATH
          echo "LDFLAGS=-L/opt/homebrew/opt/qt@5/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/qt@5/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/qt@5/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build redatam and redatamgui on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: make all

      - name: Build redatam and redatamgui on Mac
        if: matrix.os == 'macos-14'
        run: make all

      - name: Test redatam with a DIC file on Mac/Linux
        run: ./redatam test/galapagos/cg15.dic test/galapagos/dic-to-csv

      - name: Test redatam with a DICX file on Mac/Linux
        run: ./redatam test/galapagos/cg15.dicX test/galapagos/dicx-to-csv

      - name: Create DEB package on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/share/applications
          cp redatam package/usr/local/bin/
          cp redatamgui package/usr/local/bin/
          chmod +x package/usr/local/bin/redatam
          chmod +x package/usr/local/bin/redatamgui
          echo "[Desktop Entry]
          Version=1.0
          Name=Redatam GUI
          Exec=/usr/local/bin/redatamgui
          Icon=utilities-terminal
          Type=Application
          Categories=Utility;" > package/usr/share/applications/redatamgui.desktop
          mkdir -p package/DEBIAN
          echo "Package: redatam
          Version: 0.0.1
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Mauricio Pacha Vargas Sepulveda <m.sepulveda@mail.utoronto.ca>
          Depends: qtbase5-dev
          Description: Redatam and Redatam GUI" > package/DEBIAN/control
          dpkg-deb --build package redatam_0.0.1_amd64.deb

      - name: Upload DEB on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-deb
          path: |
            redatam_0.0.1_amd64.deb

      - name: Upload binaries on Mac
        if: matrix.os == 'macos-14'
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            redatam
            redatamgui
