name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.0-gtk3-dev

      - name: Set up environment on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install wxwidgets
          echo "$(brew --prefix wxwidgets)/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=$(brew --prefix wxwidgets)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install Xerces on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          chmod +x dev/01-install-xerces.sh
          ./dev/01-install-xerces.sh

      - name: Install Xerces on macOS
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x dev/01-install-xerces.sh
          ./dev/01-install-xerces.sh

      - name: Build redatam on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: make all

      - name: Build redatam and redatamgui on macOS
        if: matrix.os == 'macos-latest'
        run: make all

      - name: Create DEB package on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/share/applications
          mv redatam package/usr/local/bin/
          mv redatamgui package/usr/local/bin/
          chmod +x package/usr/local/bin/redatam
          chmod +x package/usr/local/bin/redatamgui
          echo "[Desktop Entry]
          Version=1.0
          Name=Redatam GUI
          Exec=/usr/local/bin/redatamgui
          Icon=utilities-terminal
          Type=Application
          Categories=Utility;" > package/usr/share/applications/redatamgui.desktop
          mkdir -p package/DEBIAN
          echo "Package: redatam
          Version: 0.0.1
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Mauricio Pacha Vargas Sepulveda <m.sepulveda@mail.utoronto.ca>
          Depends: libxerces-c-dev, libwxgtk3.0-gtk3-0v5
          Description: Redatam and Redatam GUI" > package/DEBIAN/control
          dpkg-deb --build package redatam_0.0.1_amd64.deb

      - name: Upload DEB on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-deb
          path: |
            redatam_0.0.1_amd64.deb
          archive: false

      - name: Upload binaries on macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            redatam
            redatamgui
