name: Test macOS Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installer:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download macOS DMG
        run: |
          curl -L -o open-redatam-mac.dmg https://github.com/pachadotdev/open-redatam/releases/download/v0.2/open-redatam-mac.dmg

      - name: Mount DMG
        run: |
          hdiutil attach open-redatam-mac.dmg

      - name: List contents of test/galapagos directory
        run: ls -l test/galapagos

      - name: Verify installation and convert DIC file
        run: |
          /Volumes/Redatam/Applications/redatam test/galapagos/cg15.dic test/galapagos/dic-to-csv
          /Volumes/Redatam/Applications/redatam test/galapagos/cg15.dicX test/galapagos/dicx-to-csv

      - name: Check conversion results
        run: |
          ls -l test/galapagos/dic-to-csv
          ls -l test/galapagos/dicx-to-csv

      - name: Install XQuartz
        run: brew install --cask xquartz

      - name: Start XQuartz and run RedatamGUI.app
        run: |
          open -a XQuartz
          export DISPLAY=:0
          sleep 3
          open /Volumes/Redatam/Applications/RedatamGUI.app
          sleep 10 # Wait for the application to start
          pkill -f XQuartz

      - name: Unmount DMG
        run: |
          hdiutil detach /Volumes/Redatam
