name: Test Ubuntu Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Ubuntu installer
        run: |
          curl -L -o open-redatam-ubuntu.deb https://github.com/pachadotdev/open-redatam/releases/download/v2.0/open-redatam-ubuntu.deb

      - name: Install Ubuntu package
        run: |
          sudo apt install -y gdebi-core
          sudo gdebi -n -q open-redatam-ubuntu.deb

      - name: Verify installation and convert DIC file
        run: |
          /usr/local/bin/redatam test/uru2011mini/uru2011mini.dic test/uru2011mini/dic-to-csv
          /usr/local/bin/redatam test/uru2011mini/uru2011mini.dicx test/uru2011mini/dicx-to-csv

      - name: Check conversion results
        run: |
          ls -l test/uru2011mini/dic-to-csv
          ls -l test/uru2011mini/dicx-to-csv
