name: Test Ubuntu Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Ubuntu installer
        run: |
          curl -L -o open_redatam_0.2_amd64.deb https://github.com/pachadotdev/open-redatam/releases/download/v0.2/open_redatam_0.2_amd64.deb

      - name: Install Ubuntu package
        run: |
          sudo apt install -y gdebi-core
          sudo gdebi -n -q open_redatam_0.2_amd64.deb

      - name: Verify installation and convert DIC file
        run: |
          /usr/local/bin/redatam test/galapagos/cg15.dic test/galapagos/dic-to-csv
          /usr/local/bin/redatam test/galapagos/cg15.dicX test/galapagos/dicx-to-csv

      - name: Check conversion results
        run: |
          ls -l test/galapagos/dic-to-csv
          ls -l test/galapagos/dicx-to-csv
